/* All free solid fontawesome icons -> https://fontawesome.com/icons?d=gallery&s=solid&m=free */

import {
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faArrowsAlt,
    faBars,
    faBell,
    faCalendarCheck,
    faChartArea,
    faChartBar,
    faChartPie,
    faChevronDown,
    faChevronUp,
    faColumns,
    faCommentDollar,
    faEdit,
    faInfo,
    faLocationArrow,
    faMapMarkerAlt,
    faMinusCircle,
    faMoneyCheckAlt,
    faPlusCircle,
    faSearch,
    faServer,
    faTable,
    faTrash,
    faUser,
    faUserLock,
    faUserNurse,
} from '@fortawesome/free-solid-svg-icons';

export const fontAwesomeSolidIcons = {
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faBars,
    faChartArea,
    faChartBar,
    faChartPie,
    faChevronDown,
    faChevronUp,
    faColumns,
    faSearch,
    faUser,
    faUserNurse,
    faCalendarCheck,
    faServer,
    faMoneyCheckAlt,
    faLocationArrow,
    faCommentDollar,
    faArrowsAlt,
    faTable,
    faPlusCircle,
    faEdit,
    faTrash,
    faUserLock,
    faInfo,
    faMapMarkerAlt,
    faBell,
    faMinusCircle,
};
